use_frameworks!
platform :ios, '10.0'

target 'AirMapGeofencingSDK-iOS' do
  pod 'AirMapGeofencingSDK', :podspec => '../AirMapGeofencingSDK.podspec'
	pod 'AirMapSDK', :git => 'https://github.com/airmap/airmapsdk-swift'
	pod 'SwiftLint'
end
